@echo off
cd /d "%~dp0"
echo [1/4] Building offline dataset (200k transitions)...
python build_dataset.py --out ../../logs/D_logs.npz --n 200000
echo [2/4] Naive offline DQN (demonstrates divergence)...
python train_naive.py --data ../../logs/D_logs.npz --config ../../configs/offline_naive.yaml
echo [3/4] CQL fix...
python train_cql.py --data ../../logs/D_logs.npz --config ../../configs/offline_cql.yaml
echo [4/4] Behavioral cloning baseline...
python train_bc.py --data ../../logs/D_logs.npz --config ../../configs/offline_bc.yaml
echo Evaluating all three...
python evaluate_offline.py --configs ../../configs/offline_naive.yaml ../../configs/offline_cql.yaml ../../configs/offline_bc.yaml
pause
